# 使用 Node.js 作为基础镜像
FROM node:latest

# 设置工作目录
WORKDIR /app

# 设置环境变量
ENV HOSTNAME=https://api.pineer.cc/updates_server_test
ENV BASE_PATH=/updates_server_test

# 复制 package.json 和 package-lock.json 到工作目录
COPY package*.json ./

# 安装项目依赖
RUN npm install

# 将项目文件复制到工作目录
# COPY . .
COPY .next ./.next

# 复制 next.config.js 到工作目录
COPY next.config.js ./

# 构建 Next.js 项目
# RUN npm run build

# 暴露 Next.js 默认端口
EXPOSE 3000

# 运行 Next.js 应用
CMD ["npm", "run" , "start"]